export const dictionary = {
    "Studio La Bandida on vuonna 2024 perustettu pieni privaattistudio Helsingissä joka sijaitsee aivan Linnanmäen kupeessa Alppilassa. Studiolla toteutetaan tatuoinnit ja kestopigmentoinnit turvallisesti, huolella ja asiakkaan toiveita kuunnellen. Olipa ajatuksenasi sitten pieni siro tatuointi tai isompi kokonaisuus vaikkapa kokonainen hiha, molemmat luonnistuvat samoin kuin mustaharmaat ja värilliset kuvat. Olet lämpimästi tervetullut juuri sellaisena kuin olet. ":{ eng:""},
    
    "Artisti / omistaja":{ eng:""},
    "Paula Annelica on kotoisin Sawon sydämestä Kuopiosta jota piirtelyt ja kaikenlaiset käsihommat ovat kiinnostaneet pienestä lähtien. Vaatetusalan artesaani- ja rakennusalan kouluista samoin kuin kuvataidekoulusta on jäänyt paperit käteen ja ensimmäiset tatuoinnit Paula teki vuonna 2010.  Tässä vaiheessa elämä kuitenkin vei ympäri maailmaa ja tatuoimiset jäi haaveeksi odottamaan oikeaa aikaansa. Monenlaisessa mukana olleena ja erinäisiä hommia tehneenä palo tatuointeihin oli kuitenkin kova ja vuoden 2019 lopulla alkoi ura tatuoijana studiolla Lahdessa. Muutamassa studiossa työskennelleenä Lahdessa ja Helsingissä, myös oman osaamisen kehittäminen laajeni kestopigmentointeihin. Tästä lähti ajatus myös oman studion perustamiselle. Paula on käynyt microblading- ja kestopigmentointikoulutukset vuonna 2024. Studiolla saattaa myös joskus olla maalauksia ym askareita menossa😊 ":{ eng:""},
    "Tyyli:  Tatuoinneissa näkyy pääsääntöisesti mustaharmaa realismi mutta värikuvat ovat yhtä lähellä sydäntä, samoin kuin pienemmät sirot kuvatkin. Kannattaa aina kysyä jos jokin muunlainen haluamasi aihe tai tyyli olisi mahdollista toteuttaa, Paula on avoin kaikenlaisille ideoille. ":{ eng:""},
    
    "Ennen tatuointia":{ eng:""},
    "Ihoa on suositeltavaa rasvata vähintään viikon ajan ennen tatuointia.":{ eng:""},
    "Iho on suositeltavaa kuoria viikon aikana 2-3 kertaa ennen tatuointiin tuloa. ":{ eng:""},
    "Nuku ja syö hyvin ennen tatuointia. Ota eväitä mukaan pitkään sessioon, studiolta löytyy jääkaappi ja kahvia on tarjolla. Vieressä on kauppa josta voi tarvittaessa hakea lisää syötävää.":{ eng:""},
    "Vältä alkoholia. Päihtyneenä tai krapulaisena ei tatuointiin kannata tulla. ":{ eng:""},
    "Tatuoitavan alueen kova kuntosalitreeni samana aamuna tai edellisenä päivänä voi tehdä tatuoimisen ottamisesta kipeämpää.":{ eng:""},
    "Varustaudu mukavilla ja sopivalla vaatetuksella. Esim olkavarren tatuoitiin hihaton paita jne. Vaatteet saattavat myös sotkeutua, joten ethän laita vaatteita joiden et toivo sotkeutuvan. ":{ eng:""},
    "Tulethan tatuointiin terveenä.":{ eng:""},
    "Joidenkin lääkitysten kohdalla (esim. verenohennuslääkeet) tai muita terveyteen liittyviä asioita, esim tulevat leikkaukset jne, on hyvä varmistaa lääkäriltäsi onko tautoiminen kannattavaa tässä kohtaa. ":{ eng:""},
    "Tatuointi on ikuinen ja tulee elämään ihon mukana ajan kuluessa. Tämä ei kuitenkaan tarkoita että tatuoinnista on jäljellä vain musta/sininen mössö parin vuoden päästä. Tähän vaikuttavat tatuoinnin tyyli, paikka ja toteutus tapa. Hyvin ja oikein tehdyt tatuoinnit kestävät aikaa todella hyvin.":{ eng:""},
    "Tatuointeja ei tehdä alle 18-vuotiaille. ":{ eng:""},
    "Tatuointi on ikuinen ja tulee aina hiukan muuttumaan ajan kanssa, iho kun vanhenee ja muuttuu, myös tatuointi muuttuu mukana. ":{ eng:""},
    "Tatuoinnilla on 6kk takuu. Jos hoito-ohjeita on noudatettu niin tatuointi paranee hyvin ja lopputulos on myös parempi. Jos jostain syystä jossain kohtaa väriä ei ole jäänyt tarpeeksi jne niin tämä korjataan ilman kuluja. Muissa tapauksissa korjauksesta veloitetaan normaali hinta. ":{ eng:""},
    
    "Hoito- ohjeet":{ eng:""},
    "Tatuoinnin jälkeen iho suojataan kemulla tai haavakalvolla. Kelmu otetaan pois 2-3 tunnin kuluttua ja kalvo poistetaan 3-4 päivän kuluttua. ":{ eng:""},
    "Haavakalvo on hengittävä ja vedenkestävä joten sen kanssa voi käydä suihkussa huoletta. Poista kalvo 3-4 päivän päästä veden alla varovasti vetämällä. Älä riuhtaise! Tämä sataa aiheuttaa iholle vaurioita ja pahimmassa tapauksessa rikkoa ihoa. Taputtele iho kuivaksi talouspaperilla tai ilma kuivaten. Levitä kevyt kerros rasvaa kuivauksen jälkeen. Voit halutessasi antaa ihon hengitellä ennen rasvausta 10-15 min. ":{ eng:""},
    "Kelmun poiston jälkeen pese tatuointi haalealla vedellä ja miedolla pesuaineella, taputtele kuivaksi talouspaperilla ja rasvaa ohuesti.":{ eng:""},
    "Voit suojata tatuoinnin ensimmäisen yön ajaksi kelmulla, mutta parhaiten iho paranee kun saa mahdollisimman paljon ilmaa, ja kelmu ei hengitä. Tästä syystä myös kelmua ei tulisi pitää ensimmäisen päivän jälkeen. ":{ eng:""},
    "Muista pestä aina kätesi ennen kuin kosket tatuointiin. ":{ eng:""},
    "Ensimmäiset kaksi viikkoa pese ja rasvaa tatuointia ohuesti 2-3 krt/ pvä.  Tai tarvittaessa voi rasvata useammin jos iho tuntuu kovin kireältä. ":{ eng:""},
    "Halutessasi voit suojata tatuointia sideharsolla ja laittaa alle hyvin rasvaa. ":{ eng:""},
    "Vältä kireitä vaatteita tatuoinnin päällä ":{ eng:""},
    "Käytä tatuoijasi suosittelemaa rasvaa tai esim Bepanthen tai Bevita-R. ":{ eng:""},
    "Älä puhdista tatuointia Desinfiointiaineilla.":{ eng:""},
    "Jos joudut suojaamaan tatuointia esim töiden takia niin voit laittaa sideharsoa ja alle rasvaa hiukan enemmän. Kuitenkin paras on jos tatuointi saa olla ilman peittämistä.":{ eng:""},
    "Tatuointi on arka ja voi olla turvonnut ja punoittava ensimmäisten päivien aikana. Samoin kuume tai kipeä olo ovat normaaleja reaktioita varsinkin pidemmän session jälkeen. Voit ottaa särkylääkettä tarvittaessa. ":{ eng:""},
    "Noin viikon kuluttua tatuoinnista alkaa irtoamaan kuollutta ihoa ja alta paljastuu uusiutunut iho joka saattaa näyttää tässä vaiheessa vielä haalealta mutta ajan kanssa palautuu normaaliin väriin. ":{ eng:""},
    "älä revi irtoavaa ihoa. Tatuointia voi suihkussa kevyesti hieroa jolloin irtoava iho lähtee helpommin pois. Luonnollinen irtoaminen on kuitenkin paras vaihtoehto.":{ eng:""},
    "Iho voi myös kutista mutta älä raavi. Kevyt läpsyttely auttaa.":{ eng:""},
    "Älä päästä lemmikkiäsi nuolemaan tatuointia. ":{ eng:""},
    "Jos paranemisessa ilmenee ongelmia ja tatuointi ei ala paranemaan vaan kipeytymään ja punoittamaan niin ole yhteydessä tatuoijaasi. ":{ eng:""},
    "Älä epäröi kysyä tatuoijaltasi jos mieltäsi askarruttaa jokin asia.":{ eng:""},
    
    "Rajoitukset":{ eng:""},
    "Hiki / Rankka treeni 2 viikkoa":{ eng:""},
    "Kuntosali 1 viikko":{ eng:""},
    "Sauna 2 viikkoa":{ eng:""},
    "Uiminen 4 viikkoa":{ eng:""},
    "Aurinko ja solarium 4 viikkoa. Jos joudut olemaan auringossa, suojaa tatuointi vaatteilla ja tatuoinnin parannuttuakin käytä suojakerroin 50. Tatuoitu iho palaa herkästi.":{ eng:""},
    "":{ eng:""},
    "Saapuminen Studiolle":{ eng:""},
    "Studio sijaitsee aivan Linnanmäen kupeessa Alppilassa. ":{ eng:""},
    "Raitiovaunut 3 ja 4 pysähtyy suoraan studion eteen. Pysäkki on ”Alppila”.":{ eng:""},
    "Sturenkadulta kulkee useita raitiovaunuja ja busseja ja siitä kävelee pari minuuttia studiolle.":{ eng:""},
    "Pasilasta matkaa on 2km ja bussi nro 23 tulee Pasilasta suoraan Sturenkadulle. ":{ eng:""},
    "Autolle pysäköintipaikkoja on paljon kadun varsilla ja on ilmaista la-su, muina aikoina maksullista. Linnanmäen parkkialue on hiukan kalliimpi kuin kadun varret. ":{ eng:""},
    "":{ eng:""},
    "Ajan varaus":{ eng:""},
    "Kerro viestiin oma nimi ja paikkakunta. ":{ eng:""},
    "Kerro  tatuointi idean lisäksi mihin ja millä tyylillä kuvan haluaisit toteutettavan. Liitä muutamia referenssi kuva mukaan. En kuitenkaan kopioi suoraan toisten tekemiä tatuointeja. Logot ym. . ovat asia erikseen.":{ eng:""},
    "Jos alueella on muita tatuointeja tai haluat peittokuvaa, ota alueesta kuva ja kerro kumpi puoli esim kädestä on kyseessä.":{ eng:""},
    "Tarkkaa hintaa on mahdoton sanoa heti alkuun ja hinta-arvio on aina arvio joka tarkentuu lopullisen suunnitelman ja toteutuksen mukaan.":{ eng:""},
    "Suunnittelu ja varausmaksu on 100e jonka maksettua varaus on sitova ja suunnittelut tapahtuvat vasta maksun jälkeen. Varausmaksu hyvitetään tatuoinnin loppusummasta.  Jos idea muuttuu kuvan suunnittelun aikana/jälkeen, tästä otetaan uusi 100-150e  suunnittelumaksu. Jos sairastut, voi aikaa siirtää kaksi kertaa samalla varausmaksulla jonka jälkeen otetaan uusi varausmaksu. ":{ eng:""},
    "Konsultaatio on maksuton ja se ei sido ottamaan vielä kuvaa. Siinä käydään ideaa tarkemmin läpi ja kysellään kaikenlaisia tarkentavia kysymyksiä jne.":{ eng:""},
    "Joskus varattu kellonaika saattaa tatuointi päivänä venyä syystä tai toisesta joten tähän on hyvä varautua. ":{ eng:""},
    "tatuointeja ei tehdä alle 18- vuotiaille.":{ eng:""},
    "Tulethan tatuoitavaksi vain terveenä.":{ eng:""},
    
    "Hinnasto":{ eng:""},
    "Tatuoinnit:":{ eng:""},
    "100e/h ":{ eng:""},
    "Walk- in kuvat alkaen 80e ":{ eng:""},
    "koko päivä 500-800e":{ eng:""},
    "Pmu:":{ eng:""},
    "150-250e":{ eng:""},
    "Varasumaksu 50-100e":{ eng:""},
    
    "Maksutavat ":{ eng:""},
    "Käteinen ja MobilePay":{ eng:""},
    }

export const translate = (phrase, language = "fin") => {
    if(language === "fin"){
        return phrase;
    }
    return dictionary[phrase][language];
} 